name: Interchain Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-basic:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-basic

  test-ibc:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-ibc
  test-packet-forward:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-packet-forward

